#pragma once

#define IDD_MFCFILEWEEK1_DIALOG 101
#define IDC_EDIT_CONTENT       1001
#define IDC_EDIT_PATH          1002
#define IDC_BTN_FOLDER         1003
#define IDC_BTN_SAVE           1004
#define IDC_BTN_LOAD           1005

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 102
#define _APS_NEXT_COMMAND_VALUE  32771
#define _APS_NEXT_CONTROL_VALUE  1006
#define _APS_NEXT_SYMED_VALUE    101
#endif
#endif
